### ISSUE TITLE
Unsupported file paths using colons

### ISSUE THREAD

**Issue by kevin4998** [omelkonian/hs-pattrans#10]
Currently in the documents folder there exists a collection of files and folders which use '**:**' (colons) in their names.  The **windows operating system** has reserved this character for alternate data streams [Source](https://en.wikipedia.org/wiki/Colon_(punctuation)#Computing). This prevents operations on windows machines with this repository.

A few files and folders have been detected in the [classical/algorithms](https://github.com/omelkonian/hs-pattrans/tree/master/docs/out/classical/algorithms) folder in documents:

- bachBWV889Fg/2016DM:SIATECCompressF1
- bachBWV889Fg/2016DM:SIATECCompressP.csv
- bachBWV889Fg/...
- beethovenOp2No1Mvt3/2016DM:SIATECCompressF1
- beethovenOp2No1Mvt3/...
- 2016DM:SIATECCompressF1.csv
- 2016DM:SIATECCompressP.csv
- ...

Not all files have been checked but these have been found so far. Is it possible to change the naming scheme of these files/folders? Thanks for all the work.

**Comment by irisyupingren** [comment]
Ah yes, it's not a problem on Ubuntu and we don't have windows machines so it never came up.
Feel free to fork and make a pull request Kevin!

**Comment by irisyupingren** [comment]
New Rendering module should have fixed this.
