### ISSUE TITLE
Parser: refactor

### ISSUE THREAD

**Issue by omelkonian** [omelkonian/hs-pattrans#14]
We need to have a more general approach to parsing, i.e. a single parsing function for all datasets (possibly requiring a 'standard' format).

**Comment by irisyupingren** [comment]
The new structure looks good! 

I wonder what you suggest when I only need to analyse one dataset.
Now it seems we only have the control to produce all Expert/Algorithm/Random at once. 

There is also the issue of the Kern dataset, and similarly with HEMANLow and HEMANHigh. 
They have subsets grouped by different composers and expert expertise. 
For example, Kern now has this structure:
- kern
  - patterns
    - algs
      - composer1
        - alg1
        - ... (have not added more algorithms yet)
      - composer2
        - alg1
      - composer3
        - alg1

Would be great to have parser extended to this case as well.

**Comment by omelkonian** [comment]
You can use the `--filters` option to select a particular piece/expert/algorithm/group.
I think parsing kern won't be a problem, if naming is done correctly you will be able to select any filters you want (same for HEMAN).

**Comment by omelkonian** [comment]
Fixed in https://github.com/omelkonian/hs-pattrans/commit/6a6d320b874ebf6549b4aa7cdb3d75f3926aaf5e
