### ISSUE TITLE
Datasets: Create separate repository

### ISSUE THREAD

**Issue by omelkonian** [omelkonian/hs-pattrans#24]
Datasets have become too big and complicate the reviewing process (e.g. in PR diffs).
Therefore, it would make sense to store them in a separate repo and use e.g. Git submodules to include them here.

**Comment by omelkonian** [comment]
@irisyupingren Could you take care of this? I guess it will be useful in other contexts.

**Comment by irisyupingren** [comment]
#25

**Comment by omelkonian** [comment]
Great, thanks!
