### ISSUE TITLE
Scale finding not identifying a test sequence

### ISSUE THREAD

**Issue by irisyupingren** [omelkonian/hs-pattrans#4]
I wrote the following dummy scale fragments in /data/hanon/patterns/ref/hanondummy2.txt
But they seem to be not picked up by the tonalTranspOf chekcer.  

pattern6
occurrence1
0.00000, 48.00000
0.25000, 50.00000
0.50000, 52.00000
0.75000, 53.00000
1.00000, 55.00000
occurrence2
8.00000, 50.00000
8.25000, 52.00000
8.50000, 53.00000
8.75000, 55.00000
9.00000, 57.00000
occurrence3
9.25000, 52.00000
9.50000, 53.00000
9.75000, 55.00000
10.00000, 57.00000
10.25000, 59.00000

**Comment by omelkonian** [comment]
### Fixed in f5165ba

We can now detect `occ1 <=>  occ3` and `occ2 <=> occ3`.
Still, `occ1 <=> occ2` is not detected, because the algorithm guesses F major (= C mixolydian), instead of C major.
This is because there is tie of matching notes, due to the missing B (59), and we pick one arbitrarily.
